FROM mambaorg/micromamba:0.15.2

COPY --chown=micromamba:micromamba environment.yml /tmp/env.yml

RUN micromamba install -y -n base -f /tmp/env.yml && \
    micromamba clean --all --yes

COPY grits setup.py README.md /tmp/

RUN ls -la /tmp

RUN python -m pip install /tmp/

RUN pytest -vx

USER root

RUN rm -r /tmp/*

RUN python -c "import grits"
